# .github/workflows/norm.yaml
name: norm
on: [push, pull_request]

jobs:

  job-norm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install Norminette
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -U norminette

    - name: Run Norminette
      working-directory: ./ex00
      run: |
        ARG=$(ls -d * | grep -v test)
        echo "$ARG"
        norminette $ARG
